# Generated by Django 4.2.5 on 2023-09-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionApp', '0004_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuario Personalizado', 'verbose_name_plural': 'Usuarios Personalizados'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/', verbose_name='Imagen de Perfil'),
        ),
    ]
